main:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Cases"
    pageRef: "categories/postgresql-cases"
    weight: 20
  - name: "Internals"
    pageRef: "categories/postgresql-internals"
    weight: 30
  - name: "Source"
    pageRef: "categories/postgresql-source-code"
    weight: 40
  - name: "Papers"
    pageRef: "categories/paper-reviews"
    weight: 50
  - name: "Notes"
    pageRef: "categories/reading-notes"
    weight: 60
  - name: "About"
    pageRef: "about"
    weight: 70

footer:
  - name: "Home"
    pageRef: "/"
    weight: 10
  - name: "Posts"
    pageRef: "/posts/"
    weight: 20
  - name: "Categories"
    pageRef: "/categories/"
    weight: 30
  - name: "Tags"
    pageRef: "/tags/"
    weight: 40
  - name: "About"
    pageRef: "/about/"
    weight: 50
  - name: "RSS"
    url: "/en/index.xml"
    pre: "rss"
    weight: 60
