main:
  - name: "首页"
    pageRef: "/"
    weight: 10
  - name: "BLOGS"
    pageRef: "/posts/"
    weight: 20
  - name: "TALKS"
    pageRef: "categories/演讲与ppt"
    weight: 30
  - name: "关于"
    pageRef: "about"
    weight: 40

subnavigation:
  - name: "案例"
    pageRef: "categories/postgresql案例"
    weight: 10
  - name: "内功"
    pageRef: "categories/postgresql内功修炼"
    weight: 20
  - name: "源码"
    pageRef: "categories/postgresql源码解析"
    weight: 30
  - name: "论文"
    pageRef: "categories/论文解读"
    weight: 40
  - name: "笔记"
    pageRef: "categories/读书笔记"
    weight: 50

footer:
  - name: "首页"
    pageRef: "/"
    weight: 10
  - name: "文章"
    pageRef: "/posts/"
    weight: 20
  - name: "分类"
    pageRef: "/categories/"
    weight: 30
  - name: "标签"
    pageRef: "/tags/"
    weight: 40
  - name: "关于"
    pageRef: "/about/"
    weight: 50
  - name: "RSS"
    url: "/index.xml"
    pre: "rss"
    weight: 60
